# Generated by Django 2.2.17 on 2020-11-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0002_auto_20201105_1649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='list',
            new_name='daftar',
        ),
    ]
