# Generated by Django 2.2.17 on 2020-11-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0003_auto_20201105_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftar',
            name='harga',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='jumlah',
            field=models.IntegerField(),
        ),
    ]
