# Generated by Django 2.2.17 on 2020-11-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datamasuk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makanan', models.CharField(max_length=225)),
                ('jumlah_masuk', models.IntegerField()),
                ('tgl_masuk', models.DateField()),
            ],
            options={
                'ordering': ['tgl_masuk'],
            },
        ),
    ]
